import { useAuth } from '../context/AuthContext';
import * as adminApi from '../services/api';
import { salesApi } from '../services/api';

/**
 * Returns the correct API functions based on user role.
 * Admin users get admin endpoints, sales users get sales endpoints.
 */
export function useApi() {
  const { isSalesUser } = useAuth();

  if (isSalesUser) {
    return {
      getDashboardStats: salesApi.getDashboard,
      getAllUsers: salesApi.getUsers,
      getAllTutors: salesApi.getTutors,
      createTutor: salesApi.createTutor,
      updateTutor: salesApi.updateTutor,
      deleteTutor: salesApi.deleteTutor,
      getAllOrders: salesApi.getOrders,
      updateOrderStatus: salesApi.updateOrderStatus,
      assignTutors: salesApi.assignTutors,
      reopenChat: salesApi.reopenChat,
      markRemainingPaid: salesApi.markRemainingPaid,
      createInstallmentPlan: salesApi.createInstallmentPlan,
      updateInstallmentPlan: salesApi.updateInstallmentPlan,
      getInstallments: salesApi.getInstallments,
      deleteInstallmentPlan: salesApi.deleteInstallmentPlan,
      markInstallmentPaid: salesApi.markInstallmentPaid,
      markAllInstallmentsPaid: salesApi.markAllInstallmentsPaid,
      getAllChats: salesApi.getChats,
      getFlaggedMessages: salesApi.getFlaggedMessages,
      getReports: salesApi.getReports,
      getSettings: salesApi.getSettings,
      updatePlan: salesApi.updatePlan,
      createCoupon: salesApi.createCoupon,
      deleteCoupon: salesApi.deleteCoupon,
      getPricingRules: salesApi.getPricingRules,
      createPricingRule: salesApi.createPricingRule,
      updatePricingRule: salesApi.updatePricingRule,
      deletePricingRule: salesApi.deletePricingRule,
      updateUrgentFee: salesApi.updateUrgentFee,
      getBannedWords: salesApi.getBannedWords,
      addBannedWord: salesApi.addBannedWord,
      deleteBannedWord: salesApi.deleteBannedWord,
      getNotifications: salesApi.getNotifications,
      markNotificationRead: salesApi.markNotificationRead,
      getUnreadCount: adminApi.getUnreadCount,
      markAllRead: adminApi.markAllRead,
      getUnreadPerOrder: adminApi.getUnreadPerOrder,
      getAllIssues: salesApi.getAllIssues,
      getIssuesUnreadCount: salesApi.getIssuesUnreadCount,
      getIssue: salesApi.getIssue,
      addIssueMessage: salesApi.addIssueMessage,
      closeIssue: salesApi.closeIssue,
      reopenIssue: salesApi.reopenIssue,
    };
  }

  return {
    getDashboardStats: adminApi.getDashboardStats,
    getAllUsers: adminApi.getAllUsers,
    getAllTutors: adminApi.getAllTutors,
    createTutor: adminApi.createTutor,
    updateTutor: adminApi.updateTutor,
    deleteTutor: adminApi.deleteTutor,
    getAllOrders: adminApi.getAllOrders,
    updateOrderStatus: adminApi.updateOrderStatus,
    assignTutors: adminApi.assignTutors,
    reopenChat: adminApi.reopenChat,
    markRemainingPaid: adminApi.markRemainingPaid,
    createInstallmentPlan: adminApi.createInstallmentPlan,
    updateInstallmentPlan: adminApi.updateInstallmentPlan,
    getInstallments: adminApi.getInstallments,
    deleteInstallmentPlan: adminApi.deleteInstallmentPlan,
    markInstallmentPaid: adminApi.markInstallmentPaid,
    markAllInstallmentsPaid: adminApi.markAllInstallmentsPaid,
    getAllChats: adminApi.getAllChats,
    getFlaggedMessages: adminApi.getFlaggedMessages,
    getReports: adminApi.getReports,
    getSettings: adminApi.getSettings,
    updatePlan: adminApi.updatePlan,
    createCoupon: adminApi.createCoupon,
    deleteCoupon: adminApi.deleteCoupon,
    getPricingRules: adminApi.getPricingRules,
    createPricingRule: adminApi.createPricingRule,
    updatePricingRule: adminApi.updatePricingRule,
    deletePricingRule: adminApi.deletePricingRule,
    updateUrgentFee: adminApi.updateUrgentFee,
    getBannedWords: adminApi.getBannedWords,
    addBannedWord: adminApi.addBannedWord,
    deleteBannedWord: adminApi.deleteBannedWord,
    getNotifications: adminApi.getNotifications,
    markNotificationRead: adminApi.markNotificationRead,
    getUnreadCount: adminApi.getUnreadCount,
    markAllRead: adminApi.markAllRead,
    getUnreadPerOrder: adminApi.getUnreadPerOrder,
    getAllIssues: adminApi.getAllIssues,
    getIssuesUnreadCount: adminApi.getIssuesUnreadCount,
    getIssue: adminApi.getIssue,
    addIssueMessage: adminApi.addIssueMessage,
    closeIssue: adminApi.closeIssue,
    reopenIssue: adminApi.reopenIssue,
  };
}
