ALTER TABLE sites
  ADD COLUMN meta_title_login VARCHAR(255) DEFAULT NULL,
  ADD COLUMN meta_desc_login VARCHAR(500) DEFAULT NULL,
  ADD COLUMN meta_title_signup VARCHAR(255) DEFAULT NULL,
  ADD COLUMN meta_desc_signup VARCHAR(500) DEFAULT NULL,
  ADD COLUMN meta_title_dashboard VARCHAR(255) DEFAULT NULL,
  ADD COLUMN meta_desc_dashboard VARCHAR(500) DEFAULT NULL,
  ADD COLUMN head_scripts TEXT DEFAULT NULL,
  ADD COLUMN body_scripts TEXT DEFAULT NULL;
