server {
    listen 80;
    root /usr/share/nginx/html/tutor;
    index index.html;

    location /tutor {
        try_files $uri $uri/ /tutor/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
