server {
    listen 80;
    root /usr/share/nginx/html/tutor;
    index index.html;

    location /tutor {
        alias /usr/share/nginx/html/tutor;
        try_files $uri $uri/ /tutor/index.html;
        index index.html;
    }
}
